### PR TITLE
Try fixing the ClobberWarning

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
@wolfv do you think this is the right approach? I am removing all `.dll` files that shouldn't be part of the output

**Comment by wolfv** [comment]
When looking at the logs I believe the offending `dll's` are installed by the ZeroMQ cmake: 

```
2021-09-03T10:20:42.0169116Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/CMake/ZeroMQConfig.cmake
2021-09-03T10:20:42.0277765Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/CMake/ZeroMQConfigVersion.cmake
2021-09-03T10:20:42.0301321Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/bin/msvcp140.dll
2021-09-03T10:20:42.1723119Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/bin/msvcp140_1.dll
2021-09-03T10:20:42.2064217Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/bin/msvcp140_2.dll
2021-09-03T10:20:42.2633674Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/bin/vcruntime140.dll
2021-09-03T10:20:42.2853657Z     -- Installing: C:/Users/VssAdministrator/AppData/Local/Temp/pip-req-build-2wudp2gy/_skbuild/win-amd64-3.8/cmake-install/bin/concrt140.dll
```

(taken from the python 3.8 win build here).

Maybe it could be fixed in that CMake? Would be slightly cleaner :)

**Comment by martinRenou** [comment]
I see :) I'll have a look at that. Thanks for the review!

**Comment by wolfv** [comment]
I wonder if `-DENABLE_CPACK=OFF` could help as argument to the ZeroMQ CMake...

**Pull request closed without merging**
